# Generated by Django 4.2.1 on 2023-06-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('metodo_envio', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de crédito'), ('efectivo', 'Efectivo'), ('paypal', 'PayPal')], max_length=100)),
            ],
        ),
    ]
