# Generated by Django 4.2.1 on 2023-06-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompra',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
