# Generated by Django 4.2.1 on 2023-06-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0002_alter_carritocompra_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompra',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
