# Generated by Django 4.0.4 on 2023-06-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fabricante', models.CharField(max_length=100, verbose_name='fabricante')),
                ('pais', models.CharField(max_length=50, verbose_name='pais')),
                ('categoria', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
